// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "llmApiUrl": string;
      "llmApiKey": string;
      "llmModel": string;
      "llmTemperature": number;
      "llmMaxTokens": number;
      "llmTimeout": number;
      "promptSummary": string;
      "promptReview": string;
    };
  }
}
